### ISSUE TITLE
A couple of typescript issues with the most recent release

### ISSUE THREAD

**Issue by scottbert** [LottieFiles/lottie-react#40]
I just upgraded react-lottie-player in my typescript project and I found that I have to specify the type for styles now - `IPlayerProps['style']` or my app fails to compile, as it doesn't like the type for `position: 'absolute'` 

```tsx
const spinnerStyles: IPlayerProps['style'] = {
  height: '2.1rem',
  width: '2.1rem',
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)'
};

<Player
      autoplay
      loop
      renderer='svg'
      src={spinnerJson}
      style={spinnerStyles}
    />
    
```

With that type added, everything runs correctly, but in the console I get a warning: 

```
Warning: Invalid DOM property `autoplay`. Did you mean `autoPlay`?
```

**Comment by karamalie** [comment]
updated to 3.0.7. The typescript enforcing on styles is actually normal for typescript div elements, i added in the htmldivelement type to the player as it would have made it easier to pass in className overrides. however ive removed that divElementType and added in just the className override. Your issue should be solved now ^^

**Comment by marr** [comment]
@karamalie I still see the `Warning: Invalid DOM property `autoplay`. Did you mean `autoPlay`?` warning with v3.0.7.
